version: '3'
services:
  backend:
    build:
      context: ./backend/nomash
      dockerfile: Dockerfile
    ports:
      - 8000:8000

  frontend:
    build:
      context: ./frontend/next
      dockerfile: Dockerfile
    ports:
      - 3000:3000

