# Generated by Django 4.2.3 on 2023-07-25 18:10

from django.db import migrations, models
import django.db.models.deletion
import funcs.postgres.enums


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(db_column='user_guid', primary_key=True, serialize=False)),
                ('birthday', models.DateTimeField(blank=True, db_column='user_birthday', null=True)),
                ('email', models.CharField(db_column='user_email', max_length=255, unique=True)),
                ('password_hash', models.CharField(blank=True, db_column='user_password_hash', max_length=64, null=True)),
                ('password', models.CharField(blank=True, db_column='user_password', max_length=64, null=True)),
                ('image_url', models.CharField(blank=True, db_column='user_image_url', max_length=255, null=True)),
                ('username', models.CharField(blank=True, db_column='user_url_profile', max_length=200, null=True)),
                ('display_name', models.CharField(blank=True, db_column='user_name', max_length=200, null=True)),
                ('login_dt', models.DateTimeField(blank=True, db_column='user_login_dt', null=True)),
                ('signup_dt', models.DateTimeField(blank=True, db_column='user_signup_dt', null=True)),
                ('suspended_at', models.DateTimeField(blank=True, db_column='suspended_at', null=True)),
            ],
            options={
                'db_table': 'user',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(db_column='order_guid', primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(blank=True, db_column='order_qty', null=True)),
                ('total_price', models.DecimalField(blank=True, db_column='order_total_price', decimal_places=2, max_digits=10, null=True)),
                ('discount', models.DecimalField(blank=True, db_column='order_discount', decimal_places=2, max_digits=10, null=True)),
                ('credit_discount', models.DecimalField(blank=True, db_column='order_credit_discount', decimal_places=2, max_digits=10, null=True)),
                ('tax', models.DecimalField(blank=True, db_column='order_tax', decimal_places=2, max_digits=10, null=True)),
                ('created', models.DateTimeField(blank=True, db_column='order_timestamp', null=True)),
                ('user', models.ForeignKey(blank=True, db_column='order_user', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='orders', to='funcs.user')),
            ],
            options={
                'db_table': 'order',
                'managed': True,
            },
        ),
    ]
