# Generated by Django 4.2.3 on 2023-07-25 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funcs', '0002_track'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='user',
            field=models.ForeignKey(blank=True, db_column='track_user', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tracks', to='funcs.user'),
        ),
    ]
